import type { LucideIcon } from 'lucide-react';
import {
    LucideArrowLeftRight,
    LucideAward,
    LucideBackpack,
    LucideBanknote,
    LucideBike,
    LucideBitcoin,
    LucideBookOpen,
    LucideBuilding2,
    LucideBus,
    LucideCalendarDays,
    LucideCar,
    LucideCarFront,
    LucideCarTaxiFront,
    LucideCode,
    LucideCoffee,
    LucideCreditCard,
    LucideDroplets,
    LucideDumbbell,
    LucideFileText,
    LucideFilm,
    LucideFlaskConical,
    LucideFlower,
    LucideFuel,
    LucideGamepad2,
    LucideGift,
    LucideGlobe,
    LucideGraduationCap,
    LucideHammer,
    LucideHandHeart,
    LucideHeartPulse,
    LucideHome,
    LucideHotel,
    LucideLandmark,
    LucideLaptop,
    LucideMapPin,
    LucideMoreHorizontal,
    LucideMusic,
    LucidePackage,
    LucidePaintbrush,
    LucideParkingSquare,
    LucidePartyPopper,
    LucidePawPrint,
    LucidePersonStanding,
    LucidePill,
    LucidePlane,
    LucideReceipt,
    LucideRefreshCw,
    LucideRoute,
    LucideSandwich,
    LucideScissors,
    LucideShield,
    LucideShieldCheck,
    LucideShieldPlus,
    LucideShirt,
    LucideShoppingBag,
    LucideShoppingCart,
    LucideSmartphone,
    LucideSmilePlus,
    LucideSofa,
    LucideSparkles,
    LucideStethoscope,
    LucideTrendingDown,
    LucideTrendingUp,
    LucideTv,
    LucideUsers,
    LucideUtensils,
    LucideUtensilsCrossed,
    LucideWifi,
    LucideWine,
    LucideWrench,
    LucideZap,
} from 'lucide-react';

import { EXPENSE_CATEGORIES, type ExpenseCategory } from './category';

type ExpenseCategoryConfig = (typeof EXPENSE_CATEGORIES)[ExpenseCategory];

export type ExpenseIconName =
    | ExpenseCategoryConfig['icon']
    | ExpenseCategoryConfig['subcategories'][number]['icon'];

export const EXPENSE_CATEGORY_ICONS = {
    ArrowLeftRight: LucideArrowLeftRight,
    Award: LucideAward,
    Backpack: LucideBackpack,
    Banknote: LucideBanknote,
    Bike: LucideBike,
    Bitcoin: LucideBitcoin,
    BookOpen: LucideBookOpen,
    Building2: LucideBuilding2,
    Bus: LucideBus,
    CalendarDays: LucideCalendarDays,
    Car: LucideCar,
    CarFront: LucideCarFront,
    CarTaxiFront: LucideCarTaxiFront,
    Code: LucideCode,
    Coffee: LucideCoffee,
    CreditCard: LucideCreditCard,
    Droplets: LucideDroplets,
    Dumbbell: LucideDumbbell,
    FileText: LucideFileText,
    Film: LucideFilm,
    FlaskConical: LucideFlaskConical,
    Flower: LucideFlower,
    Fuel: LucideFuel,
    Gamepad2: LucideGamepad2,
    Gift: LucideGift,
    Globe: LucideGlobe,
    GraduationCap: LucideGraduationCap,
    Hammer: LucideHammer,
    HandHeart: LucideHandHeart,
    HeartPulse: LucideHeartPulse,
    Home: LucideHome,
    Hotel: LucideHotel,
    Landmark: LucideLandmark,
    Laptop: LucideLaptop,
    MapPin: LucideMapPin,
    MoreHorizontal: LucideMoreHorizontal,
    Music: LucideMusic,
    Package: LucidePackage,
    Paintbrush: LucidePaintbrush,
    ParkingSquare: LucideParkingSquare,
    PartyPopper: LucidePartyPopper,
    PawPrint: LucidePawPrint,
    PersonStanding: LucidePersonStanding,
    Pill: LucidePill,
    Plane: LucidePlane,
    Receipt: LucideReceipt,
    RefreshCw: LucideRefreshCw,
    Route: LucideRoute,
    Sandwich: LucideSandwich,
    Scissors: LucideScissors,
    Shield: LucideShield,
    ShieldCheck: LucideShieldCheck,
    ShieldPlus: LucideShieldPlus,
    Shirt: LucideShirt,
    ShoppingBag: LucideShoppingBag,
    ShoppingCart: LucideShoppingCart,
    Smartphone: LucideSmartphone,
    SmilePlus: LucideSmilePlus,
    Sofa: LucideSofa,
    Sparkles: LucideSparkles,
    Stethoscope: LucideStethoscope,
    TrendingDown: LucideTrendingDown,
    TrendingUp: LucideTrendingUp,
    Tv: LucideTv,
    Users: LucideUsers,
    Utensils: LucideUtensils,
    UtensilsCrossed: LucideUtensilsCrossed,
    Wifi: LucideWifi,
    Wine: LucideWine,
    Wrench: LucideWrench,
    Zap: LucideZap,
} satisfies Record<ExpenseIconName, LucideIcon>;
